version: 2

sphinx:
  configuration: doc/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_install:
      - wget https://github.com/glotzerlab/hoomd-blue/releases/download/v4.8.2/hoomd-4.8.2.tar.gz
      - tar -xzvf hoomd-4.8.2.tar.gz
      - python doc/mock_install.py hoomd-4.8.2/hoomd src

conda:
  environment: doc/environment.yaml
