version: 2

sphinx:
  configuration: doc/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-23.11"
  jobs:
    post_install:
      - wget https://github.com/glotzerlab/hoomd-blue/releases/download/v5.4.0/hoomd-5.4.0.tar.gz
      - tar -xzvf hoomd-5.4.0.tar.gz
      - python doc/mock_install.py hoomd-5.4.0/hoomd src

conda:
  environment: doc/environment.yaml
