version: 2

sphinx:
  configuration: doc/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_install:
      - python doc/mock_install.py

conda:
  environment: doc/environment.yaml
