[workspace]
authors = ["Michael P. Howard <mphoward@auburn.edu>"]
channels = ["conda-forge"]
name = "azplugins"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[tasks]

[dependencies]
cereal = "*"
cmake = "*"
eigen = "*"
gsd = "*"
h5py = "*"
ninja = "*"
numpy = "*"
openmpi = "*"
pybind11 = "*"
pytest = "*"
python = "3.14.*"
